# Generated by Django 5.2.3 on 2025-07-01 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actors', '0001_initial'),
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('actos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='actors.actor')),
                ('genres', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='genres.genre')),
            ],
        ),
    ]
