# Generated by Django 5.2.3 on 2025-07-01 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
        ('genres', '0001_initial'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actos',
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='actors', to='actors.actor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movies', to='genres.genre'),
        ),
    ]
