# Generated by Django 5.2.3 on 2025-07-01 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_remove_movie_actors_alter_movie_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='year',
            new_name='release_date',
        ),
    ]
